enterprise_medallion:
  target: "{{ env_var('DBT_TARGET', 'dev') }}"
  outputs:
    dev:
      type: snowflake
      account: "{{ env_var('SNOWFLAKE_ACCOUNT') }}"
      user: "{{ env_var('SNOWFLAKE_USER') }}"
      password: "{{ env_var('SNOWFLAKE_PASSWORD') }}"
      role: "ROLE_TRANSFORM_DEV"
      warehouse: "WH_TRANSFORM_DEV"
      database: "ANALYTICS_DEV"
      schema: "SILVER"
      threads: 4
      client_session_keep_alive: false

    prod:
      type: snowflake
      account: "{{ env_var('SNOWFLAKE_ACCOUNT') }}"
      user: "{{ env_var('SNOWFLAKE_USER') }}"
      password: "{{ env_var('SNOWFLAKE_PASSWORD') }}"
      role: "ROLE_TRANSFORM_PROD"
      warehouse: "WH_TRANSFORM_PROD"
      database: "ANALYTICS_PROD"
      schema: "SILVER"
      threads: 4
      client_session_keep_alive: false
