enterprise_medallion:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: "{{ env_var('SNOWFLAKE_ACCOUNT') }}"
      user: "{{ env_var('SNOWFLAKE_USER') }}"
      password: "{{ env_var('SNOWFLAKE_PASSWORD') }}"
      role: "R_DEV_TRANSFORM"
      warehouse: "WH_DEV_DBT_S"
      database: "ANALYTICS_DEV"
      schema: "SILVER"
      threads: 4

    prod:
      type: snowflake
      account: "{{ env_var('SNOWFLAKE_ACCOUNT') }}"
      user: "{{ env_var('SNOWFLAKE_USER') }}"
      password: "{{ env_var('SNOWFLAKE_PASSWORD') }}"
      role: "R_PRD_TRANSFORM"
      warehouse: "WH_PRD_DBT_S"
      database: "ANALYTICS_PRD"
      schema: "SILVER"
      threads: 4
