USE ROLE R_DEV_INGEST;
USE WAREHOUSE WH_DEV_LOAD_XS;
USE DATABASE RAW_DEV;
USE SCHEMA BRONZE;

-- Streams track inserted/updated/deleted rows at table level
CREATE OR REPLACE STREAM STRM_CUSTOMERS_BRONZE ON TABLE CUSTOMERS_BRONZE;
CREATE OR REPLACE STREAM STRM_PRODUCTS_BRONZE  ON TABLE PRODUCTS_BRONZE;
CREATE OR REPLACE STREAM STRM_ORDERS_BRONZE    ON TABLE ORDERS_BRONZE;
CREATE OR REPLACE STREAM STRM_ORDER_ITEMS_BRONZE ON TABLE ORDER_ITEMS_BRONZE;
