USE ROLE R_DEV_INGEST;
USE DATABASE RAW_DEV;

CREATE OR REPLACE TASK UTIL.TSK_LOAD_ORDERS_BRONZE
  WAREHOUSE = WH_DEV_LOAD_XS
  SCHEDULE = 'USING CRON 0 */1 * * * UTC'
AS
CALL UTIL.SP_LOAD_ORDERS_BRONZE();
