USE ROLE R_DEV_INGEST;
USE DATABASE RAW_DEV;

ALTER TASK UTIL.TSK_LOAD_CUSTOMERS_BRONZE RESUME;
ALTER TASK UTIL.TSK_LOAD_PRODUCTS_BRONZE RESUME;
ALTER TASK UTIL.TSK_LOAD_ORDERS_BRONZE RESUME;
ALTER TASK UTIL.TSK_LOAD_ORDER_ITEMS_BRONZE RESUME;
