USE ROLE {{ deploy_role }};
USE DATABASE {{ raw_db }};
USE SCHEMA {{ util_schema }};

ALTER TASK TSK_LOAD_CUSTOMERS_BRONZE RESUME;
ALTER TASK TSK_LOAD_PRODUCTS_BRONZE RESUME;
ALTER TASK TSK_LOAD_ORDERS_BRONZE RESUME;
ALTER TASK TSK_LOAD_ORDER_ITEMS_BRONZE RESUME;
