USE ROLE {{ deploy_role }};
USE WAREHOUSE {{ load_wh }};
USE DATABASE {{ raw_db }};
USE SCHEMA {{ bronze_schema }};

CREATE OR REPLACE STREAM STRM_CUSTOMERS_BRONZE ON TABLE CUSTOMERS_BRONZE;
CREATE OR REPLACE STREAM STRM_PRODUCTS_BRONZE  ON TABLE PRODUCTS_BRONZE;
CREATE OR REPLACE STREAM STRM_ORDERS_BRONZE    ON TABLE ORDERS_BRONZE;
CREATE OR REPLACE STREAM STRM_ORDER_ITEMS_BRONZE ON TABLE ORDER_ITEMS_BRONZE;
