USE ROLE {{ deploy_role }};
USE DATABASE {{ raw_db }};
USE SCHEMA {{ util_schema }};

CREATE OR REPLACE TASK UTIL.TSK_LOAD_CUSTOMERS_BRONZE
  WAREHOUSE = {{ load_wh }}
  SCHEDULE = 'USING CRON 0 */1 * * * UTC'
AS
CALL UTIL.SP_LOAD_CUSTOMERS_BRONZE();


CREATE OR REPLACE TASK UTIL.TSK_LOAD_PRODUCTS_BRONZE
  WAREHOUSE = {{ load_wh }}
  SCHEDULE = 'USING CRON 0 */1 * * * UTC'
AS
CALL UTIL.SP_LOAD_PRODUCTS_BRONZE();


CREATE OR REPLACE TASK UTIL.TSK_LOAD_ORDERS_BRONZE
  WAREHOUSE = {{ load_wh }}
  SCHEDULE = 'USING CRON 0 */1 * * * UTC'
AS
CALL UTIL.SP_LOAD_ORDERS_BRONZE();


CREATE OR REPLACE TASK UTIL.TSK_LOAD_ORDER_ITEMS_BRONZE
  WAREHOUSE = {{ load_wh }}
  SCHEDULE = 'USING CRON 0 */1 * * * UTC'
AS
CALL UTIL.SP_LOAD_ORDER_ITEMS_BRONZE();
