-- Replace YOUR_USER with your Snowflake username
GRANT ROLE R_DEV_PLATFORM_ADMIN TO USER "MANJINDERSINGHFZK";

-- Optional but nice: default role/warehouse
ALTER USER "MANJINDERSINGHFZK" SET DEFAULT_ROLE = R_DEV_PLATFORM_ADMIN;
ALTER USER "MANJINDERSINGHFZK" SET DEFAULT_WAREHOUSE = WH_DEV_ADMIN_XS;
