USE ROLE R_DEV_PLATFORM_ADMIN;

ALTER TABLE ANALYTICS_DEV.GOLD.DIM_CUSTOMERS
  MODIFY COLUMN EMAIL
  SET MASKING POLICY ANALYTICS_DEV.SECURITY.MP_DEV_EMAIL;

ALTER TABLE ANALYTICS_DEV.GOLD.DIM_CUSTOMERS
  MODIFY COLUMN PHONE
  SET MASKING POLICY ANALYTICS_DEV.SECURITY.MP_DEV_PHONE;
